name = "Craft Nectar"
author = "Sewdohe & Storm_x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9454fa2bab3a5c29e92fd41d21cfc82c3bdfcdb26ac71bc38314ad6538531db1"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
