name = "Craft Nectar"
author = "Sewdohe & Storm_x & ThatEpicTragdey"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71dc4131cddb5dfef6386948a400c1492423e837e2004e713fbb14ef32154e0a"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
